### ISSUE TITLE
Singletons right= Do NOT USE Singleton Design Pattern!

### ISSUE THREAD

**Issue by PeterSommerlad** [ola-ct/singleton-demo#1]
Liebe Redaktion

Ich bin als Pattern Autor der 2. Stunde ( Pattern-oriented Software Architecture Vol.1), Mitglied des ISO C++ Standardisierungskommitees und Professor für Informatik/Software Engineering total erschrocken, als ich im aktuellen Heft einen Artikel über "Singletons sauber in C++ programmieren" gesehen habe. Dazu gibt es nur eine Aussage "Tue es nicht!". Und das weiss die Software Pattern Community seit mindestens 20 Jahren. Warum wird dieser Verhinderer von gutem Design immer noch genutzt? 

Ich habe die Theorie,dass viele, die Software Design unterrichten, kein Software Design machen und bei Design Patterns sich das mit dem einfachsten Klassendiagramm aussuchen, also Singleton, ohne sich irgendwelche Sekundärliteratur dazu anzuschauen und ohne Software Design praktisch zu beherrschen. Jeder der in eine solche Schule geht, wird sich das erste und einfachste merken und dann im Beruf anwenden. Dieser Teil der Software Krise ist hausgemacht!

Veränderbare globale Variablen sind in heutigem C++17 ( der Artikel referenziert den Draft des C++14 Standards) mit multi threading zu vermeiden. Die Serialisierung der out() Funktion benötigt keinen Unique_lock, sondern ein einfacherer scope_lock reicht, aber beides ist unzureichend, weil data races auch schon beim init passieren können (nicht jedoch bei einem Konstruktor). C++20 wird für die Synchronisation von output streams ferner mit std::osyncstream einen passenderen Mechanismus bieten ( en.cppreference.com/w/cpp/io/basic_osyncstream ).

Aber auch wenn kein multi threading verwendet wird, sind Singletons generell ein Verhinderer von testbarem code aufgrund der versteckten globalen Abhängigkeiten. Das gilt auch für die beliebten globalen variablen std::cin und std::cout. Meine Studierenden lernen, dass diese globalen variablen nur in der main() Funktion benutzt werden dürfen und alle Funktionen/Klassen, die io machen müssen dazu den passenden stream als parameter erhalten.

Meiner Meinung nach wäre eigentlich eine Gegendarstellung zu diesem Artikel notwendig, weil er gefährliche/"giftige" Praktiken postuliert.

Gruss
Peter Sommerlad.

**Comment by 607011** [comment]
Danke für Ihren Input. Eine kurze Diskussion, wann Singletons sinnvoll sind (mir fallen nicht viele Fälle ein) und wann man besser die Finger lassen sollte (fast immer), steht im Kasten.

**Comment by PeterSommerlad** [comment]
Aber bitte gar nicht erst solch schlechten Code zeigen!
