### ISSUE TITLE
Build error: Undefined reference to Logger::initMtx

### ISSUE THREAD

**Issue by matzeschmid** [ola-ct/singleton-demo#3]
Hallo.

Um die "lazylogger" Variante zu verwenden, musste ich `lazylogger.cpp` um die Initialisierung von `Logger::initMtx` ergänzen.

`std::mutex Logger::initMtx;`

OS: Win10
Toolchain: Visual Studio 2015 bzw. MinGw 7.3

Gruß,
Mathias

**Comment by 607011** [comment]
Seltstam, `initMtx` ist seit 376c9ecf214f5fa6c066bde47e75b65eb58d58dc (vor 11 Tagen eingecheckt) drin.

**Comment by matzeschmid** [comment]
Korrekt, `initMtx` ist in der Klassendefinition aufgeführt. Da `initMtx` aber als `static` deklariert ist, muss es außerhalb der Klasse definiert werden.

In `lazylogger.hpp` fehlt noch `#include <mutex>`.
